// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zuma.Web.DataAccess;

#nullable disable

namespace Zuma.Web.Migrations
{
    [DbContext(typeof(ZumaDBContext))]
    [Migration("20230207200911_First Build")]
    partial class FirstBuild
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Zuma.Web.Models.VoteBlock", b =>
                {
                    b.Property<string>("VoteBlockId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastVotePackHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VoteBlockIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VotePack")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VotePackHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VoteBlockId");

                    b.ToTable("VoteBlocks");
                });

            modelBuilder.Entity("Zuma.Web.Models.VotePack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<char?>("VoteBlockStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoteDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoteForAssembly")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoteForGovernor")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoteForPresident")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoteForReps")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoteForSenate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoteLocation")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VoterAge")
                        .HasColumnType("INTEGER");

                    b.Property<char?>("VoterGender")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoterOccupation")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoterPU")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VotePacks");
                });
#pragma warning restore 612, 618
        }
    }
}
